### ISSUE TITLE
Hi, when i try to run it, it show the error below

### ISSUE THREAD

**Issue by bookkaaa** [traderpy/metatrader5-dash#1]
C:\Users\shirl\AppData\Local\Microsoft\WindowsApps\python3.10.exe C:\Users\shirl\OneDrive\Documentos\GitHub\metatrader5-dash\app\application.py 
Traceback (most recent call last):
  File "C:\Users\shirl\OneDrive\Documentos\GitHub\metatrader5-dash\app\application.py", line 16, in <module>
    options=[{'label': symbol, 'value': symbol} for symbol in get_symbol_names()],
  File "C:\Users\shirl\OneDrive\Documentos\GitHub\metatrader5-dash\app\mt5_funcs.py", line 25, in get_symbol_names
    symbols_df = pd.DataFrame(symbols, columns=symbols[0].asdict().keys())
TypeError: 'NoneType' object is not subscriptable

Process finished with exit code 1

**Comment by imadaris** [comment]
i guess this is a hack! the script can possibly take sensitive information from your mt5 .. because it is not opening in localhost as it shows in the video, instead it opens your mt5 application ! be cautious
